apiVersion: rook.io/v1alpha1
kind: Filesystem
metadata:
  name: registryfs
  namespace: rook
spec:
  metadataPool:
    replicated:
      size: 3
  dataPools:
    - replicated:
        size: 3
  metadataServer:
    activeCount: 1
    activeStandby: true
